import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Build output, the Deno edge function (separate runtime, not the Vite app),
    // and large generated files that are regenerated by tooling.
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "supabase/functions/**",
      "**/routeTree.gen.ts",
      "src/integrations/supabase/types.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // Tracked as warnings (visible, non-blocking) rather than off or error:
      // legacy `any` is being reduced incrementally (Phase 3 regenerates the DB
      // types), and surfacing unused vars/expressions flags dead code without
      // turning the lint gate red on day one.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-unused-expressions": "warn",
    },
  },
  eslintPluginPrettier,
  {
    // Keep format drift visible without blocking feature verification. The repo
    // already treats incremental cleanup findings as warnings, and routeTree plus
    // generated Supabase types are ignored above.
    rules: { "prettier/prettier": "warn" },
  },
);
