/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClonesNewRouteImport } from './routes/clones.new'
import { Route as ClonesCloneIdRouteImport } from './routes/clones.$cloneId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClonesNewRoute = ClonesNewRouteImport.update({
  id: '/clones/new',
  path: '/clones/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClonesCloneIdRoute = ClonesCloneIdRouteImport.update({
  id: '/clones/$cloneId',
  path: '/clones/$cloneId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/clones/$cloneId': typeof ClonesCloneIdRoute
  '/clones/new': typeof ClonesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/clones/$cloneId': typeof ClonesCloneIdRoute
  '/clones/new': typeof ClonesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/clones/$cloneId': typeof ClonesCloneIdRoute
  '/clones/new': typeof ClonesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/dashboard' | '/clones/$cloneId' | '/clones/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/clones/$cloneId' | '/clones/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clones/$cloneId'
    | '/clones/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ClonesCloneIdRoute: typeof ClonesCloneIdRoute
  ClonesNewRoute: typeof ClonesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clones/new': {
      id: '/clones/new'
      path: '/clones/new'
      fullPath: '/clones/new'
      preLoaderRoute: typeof ClonesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clones/$cloneId': {
      id: '/clones/$cloneId'
      path: '/clones/$cloneId'
      fullPath: '/clones/$cloneId'
      preLoaderRoute: typeof ClonesCloneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ClonesCloneIdRoute: ClonesCloneIdRoute,
  ClonesNewRoute: ClonesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
