/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as FleetManagerRouteImport } from './routes/fleet-manager'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CloudflareRouteImport } from './routes/cloudflare'
import { Route as CascadesRouteImport } from './routes/cascades'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksFleetDriftRouteImport } from './routes/hooks.fleet-drift'
import { Route as ClonesNewRouteImport } from './routes/clones.new'
import { Route as ClonesCloneIdRouteImport } from './routes/clones.$cloneId'
import { Route as CascadesEventIdRouteImport } from './routes/cascades.$eventId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetManagerRoute = FleetManagerRouteImport.update({
  id: '/fleet-manager',
  path: '/fleet-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudflareRoute = CloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadesRoute = CascadesRouteImport.update({
  id: '/cascades',
  path: '/cascades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksFleetDriftRoute = HooksFleetDriftRouteImport.update({
  id: '/hooks/fleet-drift',
  path: '/hooks/fleet-drift',
  getParentRoute: () => rootRouteImport,
} as any)
const ClonesNewRoute = ClonesNewRouteImport.update({
  id: '/clones/new',
  path: '/clones/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClonesCloneIdRoute = ClonesCloneIdRouteImport.update({
  id: '/clones/$cloneId',
  path: '/clones/$cloneId',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadesEventIdRoute = CascadesEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => CascadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/cascades': typeof CascadesRouteWithChildren
  '/cloudflare': typeof CloudflareRoute
  '/dashboard': typeof DashboardRoute
  '/fleet-manager': typeof FleetManagerRoute
  '/modules': typeof ModulesRoute
  '/settings': typeof SettingsRoute
  '/cascades/$eventId': typeof CascadesEventIdRoute
  '/clones/$cloneId': typeof ClonesCloneIdRoute
  '/clones/new': typeof ClonesNewRoute
  '/hooks/fleet-drift': typeof HooksFleetDriftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/cascades': typeof CascadesRouteWithChildren
  '/cloudflare': typeof CloudflareRoute
  '/dashboard': typeof DashboardRoute
  '/fleet-manager': typeof FleetManagerRoute
  '/modules': typeof ModulesRoute
  '/settings': typeof SettingsRoute
  '/cascades/$eventId': typeof CascadesEventIdRoute
  '/clones/$cloneId': typeof ClonesCloneIdRoute
  '/clones/new': typeof ClonesNewRoute
  '/hooks/fleet-drift': typeof HooksFleetDriftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/cascades': typeof CascadesRouteWithChildren
  '/cloudflare': typeof CloudflareRoute
  '/dashboard': typeof DashboardRoute
  '/fleet-manager': typeof FleetManagerRoute
  '/modules': typeof ModulesRoute
  '/settings': typeof SettingsRoute
  '/cascades/$eventId': typeof CascadesEventIdRoute
  '/clones/$cloneId': typeof ClonesCloneIdRoute
  '/clones/new': typeof ClonesNewRoute
  '/hooks/fleet-drift': typeof HooksFleetDriftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/auth'
    | '/cascades'
    | '/cloudflare'
    | '/dashboard'
    | '/fleet-manager'
    | '/modules'
    | '/settings'
    | '/cascades/$eventId'
    | '/clones/$cloneId'
    | '/clones/new'
    | '/hooks/fleet-drift'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/auth'
    | '/cascades'
    | '/cloudflare'
    | '/dashboard'
    | '/fleet-manager'
    | '/modules'
    | '/settings'
    | '/cascades/$eventId'
    | '/clones/$cloneId'
    | '/clones/new'
    | '/hooks/fleet-drift'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/auth'
    | '/cascades'
    | '/cloudflare'
    | '/dashboard'
    | '/fleet-manager'
    | '/modules'
    | '/settings'
    | '/cascades/$eventId'
    | '/clones/$cloneId'
    | '/clones/new'
    | '/hooks/fleet-drift'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  CascadesRoute: typeof CascadesRouteWithChildren
  CloudflareRoute: typeof CloudflareRoute
  DashboardRoute: typeof DashboardRoute
  FleetManagerRoute: typeof FleetManagerRoute
  ModulesRoute: typeof ModulesRoute
  SettingsRoute: typeof SettingsRoute
  ClonesCloneIdRoute: typeof ClonesCloneIdRoute
  ClonesNewRoute: typeof ClonesNewRoute
  HooksFleetDriftRoute: typeof HooksFleetDriftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-manager': {
      id: '/fleet-manager'
      path: '/fleet-manager'
      fullPath: '/fleet-manager'
      preLoaderRoute: typeof FleetManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloudflare': {
      id: '/cloudflare'
      path: '/cloudflare'
      fullPath: '/cloudflare'
      preLoaderRoute: typeof CloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascades': {
      id: '/cascades'
      path: '/cascades'
      fullPath: '/cascades'
      preLoaderRoute: typeof CascadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/fleet-drift': {
      id: '/hooks/fleet-drift'
      path: '/hooks/fleet-drift'
      fullPath: '/hooks/fleet-drift'
      preLoaderRoute: typeof HooksFleetDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clones/new': {
      id: '/clones/new'
      path: '/clones/new'
      fullPath: '/clones/new'
      preLoaderRoute: typeof ClonesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clones/$cloneId': {
      id: '/clones/$cloneId'
      path: '/clones/$cloneId'
      fullPath: '/clones/$cloneId'
      preLoaderRoute: typeof ClonesCloneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascades/$eventId': {
      id: '/cascades/$eventId'
      path: '/$eventId'
      fullPath: '/cascades/$eventId'
      preLoaderRoute: typeof CascadesEventIdRouteImport
      parentRoute: typeof CascadesRoute
    }
  }
}

interface CascadesRouteChildren {
  CascadesEventIdRoute: typeof CascadesEventIdRoute
}

const CascadesRouteChildren: CascadesRouteChildren = {
  CascadesEventIdRoute: CascadesEventIdRoute,
}

const CascadesRouteWithChildren = CascadesRoute._addFileChildren(
  CascadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  CascadesRoute: CascadesRouteWithChildren,
  CloudflareRoute: CloudflareRoute,
  DashboardRoute: DashboardRoute,
  FleetManagerRoute: FleetManagerRoute,
  ModulesRoute: ModulesRoute,
  SettingsRoute: SettingsRoute,
  ClonesCloneIdRoute: ClonesCloneIdRoute,
  ClonesNewRoute: ClonesNewRoute,
  HooksFleetDriftRoute: HooksFleetDriftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
